### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by necrogami**
Updating readme to reflect current method of installing npm dependencies and running webpack instead of gulp.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks!

**Comment by sebastiandedeyne** [comment]
Copying the webpack config isn't necessary iirc, since it's referenced in the script's command https://github.com/spatie/dashboard.spatie.be/blob/master/package.json#L4

**Comment by necrogami** [comment]
Except every time i run webpack it throws an error that there isn't a webpack.config.js file

**Comment by sebastiandedeyne** [comment]
You're supposed to run `yarn run dev`, or `npm run dev`. That's how it's set up in a vanilla Laravel installation too.

**Pull request merged**
