### PR TITLE
New Relic server monitoring

### PR DESCRIPTION
**Pull request by viezel**
This adds support for getting server monitoring stats into the dashboard.

### CODE REVIEW

**Comment by freekmurze** [comment]
Hi,

thank you for this, but we're currently not accepting 3th party widgets.

If you put the code for your widget in a separate repo, I'll be more than happy to link to it in our readme.

**Comment by viezel** [comment]
oh I see. no worries. just want to give some back.

**Comment by viezel** [comment]
ill make a few new components here https://github.com/viezel/dashboard.spatie.be in the next coming days.

**Comment by freekmurze** [comment]
Ok, let me know when you're done with them and I'll link to it in our readme.

If possible try to write a extensive readme on how people can install / use your components in the dashboard. Users of our dashboard (and I) will be grateful for that. 👍

**Comment by viezel** [comment]
@freekmurze there you go: https://github.com/viezel/dashboard.spatie.be

New Components:

- New Relic Server list (CPU, mem, disk, IO)
- New Relic Throughput graph (request pr minute)
- GitLab Builds
- Wunderlist Tasks
- Bugsnag Errors
- Zoho CRM events and potentials

**Comment by freekmurze** [comment]
Very cool! Can you post a screenshot of your dashboard? I'm curious how it looks like 😄

**Comment by viezel** [comment]
now also :

- Laravel News feed

dashboard

**Comment by freekmurze** [comment]
Very nice, thanks!

**Pull request closed without merging**
