### PR TITLE
Add NMBS trains tile

### PR DESCRIPTION
**Pull request by Rias500**
This adds a train tile with 2 environment variables:

`TRAIN_STATION=` for example `Antwerpen-Berchem`
`TRAIN_EXCLUDED=` comma separated list of excluded departures (for example `Antwerpen-Centraal`

Looks similar to the Velo tile

image

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks @Rias500

**Comment by driesvints** [comment]
Sweet! Something which could also be nice in addition to the exclude list would be a whitelist of destinations which you're only interested in.

**Comment by Rias500** [comment]
That's what @freekmurze refactored it too in the latest commits, it now displays connections which is a much better solution 😊

**Comment by driesvints** [comment]
Nice!

**Pull request merged**
